parameters:
    widget_factory.class: BRS\CoreBundle\Core\Widget\WidgetFactory
    
services:
    widget_factory:
        class:     %widget_factory.class%
        calls:
        - [ setContainer,  [@service_container] ]
    brs.twig.extension:
        class: BRS\CoreBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }